id: P009094
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG4273
  title: ནང་བསྟན་ཤེས་རིག་གི་མདུན་ལམ་གླེང་བའི་འབོལ་རྩོམ
  author: ''
  volumes:
    a3f6cb59552649fcb5a3960a1e0fb79e:
      image_group_id: I1KG4997
      title: ''
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
